version: "3"

networks:
  backend:
    driver: bridge

services:
  app:
    build: ./app
    volumes:
      - ./app:/usr/src/app
    environment:
      - MIX_ENV=dev
    ports:
      - 4000:4000
    stdin_open: true
    tty: true
    command: sh -c "mix phx.server --no-halt"
    network_mode: "bridge"
    networks:
      - backend

  db:
    build: ./db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=my_app_dev
    ports:
      - 5432:5432
    volumes:
      - ./db/postgres/tmp/data:/var/lib/postgresql/data
    restart: always
    networks:
      - backend
